# Generated by Django 4.1.2 on 2022-11-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('R', 'review'), ('C', 'clubpost'), ('A', 'advertisement')], max_length=1, null=True, verbose_name='글 종류'),
        ),
    ]
