# Generated by Django 4.1.2 on 2022-11-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_type'),
        ('post', '0002_initial'),
    ]

    operations = [
    ]
