# Generated by Django 4.1.2 on 2022-11-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('post', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.major'),
        ),
        migrations.AddField(
            model_name='clubpost',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='club.club'),
        ),
        migrations.AddField(
            model_name='clubpost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clubpost', to='post.post'),
        ),
        migrations.AddField(
            model_name='club',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.division', verbose_name='구분'),
        ),
    ]
