# Generated by Django 4.1.3 on 2022-12-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='recruitment_period_end',
            field=models.DateTimeField(null=True, verbose_name='모집 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='club',
            name='recruitment_period_start',
            field=models.DateTimeField(null=True, verbose_name='모집 시작 날짜'),
        ),
    ]
