# Generated by Django 4.1.2 on 2022-11-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('club', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.major'),
        ),
    ]
