# Generated by Django 4.1.2 on 2022-11-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
        ('relationship', '0004_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap', to='post.post', verbose_name='스크랩 하는 글'),
        ),
    ]
