version: '3'
services:

    nginx:
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./webapp:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        build: ./webapp
        image: docker-server/django
        restart: always
        command: bash -c
            "python manage.py makemigrations
            && python manage.py migrate
            && uwsgi --ini uwsgi.ini"
        volumes:
          - ./webapp:/srv/docker-server
          - ./log:/var/log/uwsgi
        depends_on:
          - mysql

    mysql:
      image: mysql:8.0
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        TZ: Asia/Seoul
      command: # 명령어 실행
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./data/:/var/lib/mysql