version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.production
    image: docker-server/nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./webapp:/srv/docker-server
      - ./log:/var/log/nginx
      - staticfiles:/srv/static
      - mediafiles:/srv/media
    depends_on:
      - django
    links:
      - django
    entrypoint:
      - /docker-entrypoint.production.sh

  django:
    build:
      context: ./webapp
      dockerfile: ./Dockerfile.production
    image: docker-server/django
    restart: always
    entrypoint:
      - /docker-entrypoint.production.sh
    volumes:
      - ./webapp:/srv
      - staticfiles:/srv/static
      - mediafiles:/srv/media

volumes:
  staticfiles:
  mediafiles:

