version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.production
    image: docker-server/nginx
    restart: always
    ports:
      - "80:80"

    depends_on:
      - django
    links:
      - django
    entrypoint:
      - /docker-entrypoint.production.sh
    volumes:
      - ./log:/var/log/nginx
      - ./webapp/staticfiles:/static
      - ./webapp/mediafiles:/media

  django:
    build:
      context: ./webapp
      dockerfile: ./Dockerfile.production
    image: docker-server/django
    restart: always
    entrypoint:
      - /docker-entrypoint.production.sh
    volumes:
      - ./webapp:/srv
      - ./webapp/staticfiles:/srv/static
      - ./webapp/mediafiles:/srv/media

volumes:
  staticfiles:
  mediafiles:

