# Generated by Django 4.1.2 on 2022-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_major_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(max_length=40, null=True, verbose_name='학부'),
        ),
        migrations.AlterField(
            model_name='major',
            name='sub_major',
            field=models.CharField(max_length=40, null=True, verbose_name='전공'),
        ),
    ]
