clubs = [
  {
    "division": None,
    "name": "아우성",
    "intro": "1985년부터 이어온 민중노래패로, 현재는 주로 밴드 활동을 하고 있습니다!",
    "curriculum": "동아리방을 방문하면 누구든 자유롭게 악기를 배울 수 있고, 모두가 함께하는 정기공연과 신입부원들의 실력을 향상할 수 있는 워크샵이 준비되어있습니다.",
    "signup_condition": "",
    "representative_number": "",
    "place": "복지관 121호",
    "members_count": 160,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "ARROW",
    "intro": "1985년부터 이어온 민중노래패로, 현재는 주로 밴드 활동을 하고 있습니다!",
    "curriculum": "동아리방을 방문하면 누구든 자유롭게 악기를 배울 수 있고, 모두가 함께하는 정기공연과 신입부원들의 실력을 향상할 수 있는 워크샵이 준비되어있습니다.",
    "signup_condition": "",
    "representative_number": "",
    "place": "복지관 213호",
    "members_count": 0,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "레이저백스",
    "intro": "미식축구부입니다",
    "curriculum": " 매년 9월부터 전국대회가 있어서 매학기 초에 신입부원을 받고 일주일에 두번 운동하고 한번 세미나를 하며 여름방학에는 합숙도 가고 같이 놀러도 가고 하며 친목도 다집니다. 시즌중에는 같이 대회에 출전합니다.",
    "signup_condition": "",
    "representative_number": "",
    "place": "복지관 235호",
    "members_count": 30,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "북악 검우회",
    "intro": "검도합니다",
    "curriculum": "특별하게 정해진 커리큘럼은 없어요! 그래서 모집기간 중 어느때나 들어오셔도 편하게 함께 하실 수 있습니다 :) 시험기간이 아닐 때엔 매주 정기 운동 하는데, 편하신 요일에 나오시면 돼요!",
    "signup_condition": "",
    "representative_number": "",
    "place": "복지관 236호",
    "members_count": 50,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "더뮤지컬",
    "intro": "해마다 정기공연을 올리고 뮤지컬 단관 등을 하는 교내 유일 뮤지컬 중앙동아리입니다.",
    "curriculum": "여름방학 중 정기공연을 하고 학기 중에는 뮤지컬 단관을 합니다.",
    "signup_condition": "",
    "representative_number": "01030868643",
    "place": "복지관 115호",
    "members_count": 80,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "손말사랑회",
    "intro": "수어를 배우고 장애인권에 대해 관심을 가진 사람들이 모인 곳입니다!",
    "curriculum": "약 6주정도는 수어 수업을 하고, 한 주는 장애인권세미나를 개최해 다 같이 장애인의 여러 문제에 대해 생각해보는 시간을 갖습니다",
    "signup_condition": "",
    "representative_number": "",
    "place": "복지관 118호",
    "members_count": 50,
    "logo": "",
    "pamphlet": "",
  }, {
    "division": None,
    "name": "손말사랑회",
    "intro": "수어를 배우고 장애인권에 대해 관심을 가진 사람들이 모인 곳입니다!",
    "curriculum": "약 6주정도는 수어 수업을 하고, 한 주는 장애인권세미나를 개최해 다 같이 장애인의 여러 문제에 대해 생각해보는 시간을 갖습니다",
    "signup_condition": "",
    "representative_number": "",
    "place": "복지관 118호",
    "members_count": 50,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "윈드밀스",
    "intro": "윈드밀스는 국민대학교 유일무이한 야구 중앙동아리 입니다.",
    "curriculum": "커리큘럼은 없고 매년 2개의 대회는 고정으로 참여하고 그 외에 매주 체계적인 정기 연습과 다른 여러가지 대회를 출전합니다",
    "signup_condition": "",
    "representative_number": "",
    "place": "복지관 132호",
    "members_count": 70,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "북악기우회",
    "intro": "바둑과 보드게임",
    "curriculum": "mt 및 대학간 여러 바둑행사 참여",
    "signup_condition": "",
    "representative_number": "",
    "place": "복지관 226호",
    "members_count": 0,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "미르택견",
    "intro": "택견은 유연하고 율동적인 춤과 같은 동작으로 상대를 공격하거나 다리를 걸어 넘어뜨리는 ‘한국 전통 무술’인데요. 부드러운 인상을 풍기면서도 힘이 느껴지는 아주 매력적인 무술입니다. 택견 활동은 종합복지관 1층에 있는 무도실에서 진행하며 활동 외에도 MT, 고려대학교 택견동아리와의 교류 활동, 동아리방에서의 보드게임, 빔프로젝터로 다같이 영화, 축구경기 관람 등 동아리원들끼리 친하게 지낼 수 있는 편한 동아리입니다:)",
    "curriculum": "정확하게 정해져 있지 않습니다(보통 운동 진행 시 스트레칭, 간단한 몸풀기, 기본적인 택견 기술 동작 익히기, 대련 등으로 진행합니다)",
    "signup_condition": "",
    "representative_number": "010-8407-0339",
    "place": "복지관 246호",
    "members_count": 40,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "울림패",
    "intro": "풍물패 중앙동아리로 풍물놀이 공연을 준비하고 공연하는 공연동아리입니다.",
    "curriculum": "배우고 싶은 악기를 선택하고 각 악기 선배들에게 악기를 배웁니다. 그 후에 울림패에서 공연하는 1부,대동판 앉은 반 등 가락을 배워 5월,11월 공연을 진행합니다.",
    "signup_condition": "",
    "representative_number": "010-8407-0339",
    "place": "복지관 125호",
    "members_count": 40,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "KMTC",
    "intro": "부원들에게 테니스를 가르쳐주고 같이 게임하면서 타 대학과의 대회에 출전하고 있습니다.",
    "curriculum": "신입부원들 중에 테니스를 처음 쳐보거나 아직 실력이 미숙한 친구들에게 트레이닝부의 학생들이 테니스를 가르쳐주고 있습니다. 이 외의 다른 커리큘럼은 없습니다.",
    "signup_condition": "",
    "representative_number": "010-3362-6967",
    "place": "테니스 코트 옆 건물",
    "members_count": 140,
    "logo": "",
    "pamphlet": "",
  },
  {
    "division": None,
    "name": "GG",
    "intro": "국민대학교 이스포츠 동아리입니다! 모든 종류의 게임을 다루고 실력에 관계 없이 게임을 재밌게 즐기는 것을 목적으로 합니다! ",
    "curriculum": "커리큘럼은 없고 한 학기에 동아리의 주된 행사는 MT, 국민대 LCK, 게임 내전, 정기 모임 등이 있습니다! ",
    "signup_condition": "",
    "representative_number": "010-5196-7300",
    "place": "복지관 219호",
    "members_count": 93,
    "logo": "",
    "pamphlet": "",
  },
]