# Generated by Django 4.1.3 on 2022-11-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club', verbose_name='동아리명'),
        ),
    ]
