# Generated by Django 4.1.2 on 2022-11-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_initial'),
        ('ad', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club', verbose_name='동아리명'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_club',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
