# Generated by Django 4.1.2 on 2022-11-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_advertisement_club_advertisement_is_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='is_club',
        ),
    ]
