FROM nginx:latest
# nginx 설치

COPY ./develop/nginx.conf /etc/nginx/nginx.conf

COPY wait-for-it.sh /wait-for-it.sh

# Copy Entrypoint Script
COPY ./develop/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh