FROM nginx:latest
# nginx 설치

COPY ./production/nginx.conf /etc/nginx/nginx.conf

COPY wait-for-it.sh /wait-for-it.sh

# Copy Entrypoint Script
COPY ./production/docker-entrypoint.production.sh /docker-entrypoint.production.sh
RUN chmod +x /docker-entrypoint.production.sh