FROM nginx:latest
# nginx 설치

COPY ./production/nginx.conf /etc/nginx/nginx.conf
# Configure Nginx

#COPY ./production/nginx-app.conf /etc/nginx/sites-available/
#
#RUN mkdir -p /etc/nginx/sites-enabled/\
#    && ln -s /etc/nginx/sites-available/nginx-app.conf /etc/nginx/sites-enabled/

CMD ["nginx", "-g", "daemon off;"]
